### ISSUE TITLE
Hantering av kvalitetsflaggor

### ISSUE THREAD

**Issue by jonatanmindroad** [nodc-sweden/fyskemqc#3]
- [x] Output ska visa kvalitetsflaggor i indata samt från automattester och visuell granskning.

- [x] Totalflagga ska sättas dynamiskt från övriga flaggor:
    - Om manuell QC är utförd (flagga != 0) ska total ha samma värde som manuell.
    - Annars används det sämsta värdet i inkommande och automatiska.

## Rankning av flaggor
Stigande ordning vid jämförelse av flaggor:

| Flaggrankning |
|---------------|
| NO_QC_PERFORMED |
| BAD_DATA |
| MISSING_VALUE |
| INTERPOLATED_VALUE |
| NOMINAL_VALUE |
| BELOW_DETECTION |
| VALUE_CHANGED |
| BAD_DATA_CORRECTABLE |
| PROBABLY_GOOD_DATA |
| GOOD_DATA |

# Länkade ärenden
- Utbrutet ärende: #18

**Comment by ylvaeSMHI** [comment]
Flaggningen ska följa QC Oceanografi och Seadatanet: 

![image](https://github.com/nodc-sweden/fyskemqc/assets/145473927/c925f420-38d0-46fe-9f6d-92279fcd6957)

Flaggningen ska utföras på en sträng enligt följande: <IN><AUTOMATISK><VISUELL> d.v.s. till exempel så här 0_12020_4

Automtisk flaggning ska följa testordning som QC Oceanografi har.
